/* ********************************************************************** */
/*                                                                        */
/*   FONT.H                                                               */
/*                                                                        */
/* ********************************************************************** */

#ifndef __FONT_H__
#define __FONT_H__

/* -- PUBLIC DATA DECLARATIONS ------------------------------------------ */

extern unsigned char BitmapFont[224][8];
extern unsigned short *VectorFont[256];
extern unsigned short *VectorFontIEEE[32];

#endif

/* -- END --------------------------------------------------------------- */
