/* ********************************************************************** */
/*                                                                        */
/*   RESOLUTN.H                                                           */
/*                                                                        */
/* ********************************************************************** */

#ifndef __RESOLUTN_H__
#define __RESOLUTN_H__

/* -- HEADER FILES ------------------------------------------------------ */

#include "global.h"

/* -- PUBLIC DATA DECLARATIONS ------------------------------------------ */

extern unsigned short ResolutionX;
extern unsigned short ResolutionY;
extern unsigned short ResolutionMaxXY;
extern char DriverInfoString[];

#endif

/* -- END --------------------------------------------------------------- */
